// Run INSTALL_NTK_V13.bat before publishing this file.
window.NTK_PUBLIC_KEY_B64 = "RUN_INSTALLER_FIRST";
window.NTK_PUBLIC_KEYS = ["RUN_INSTALLER_FIRST"];
window.NTK_GOVERNMENT = "GOVERNMENT OF UNION TERRITORY OF JAMMU & KASHMIR";
window.NTK_DEPARTMENT = "DEPARTMENT OF REVENUE";
window.NTK_OFFICE_NAME = "OFFICE OF THE NAIB TEHSILDAR KRALGUND";
window.NTK_DESIGNATION = "EXECUTIVE MAGISTRATE 1ST CLASS KRALGUND";
window.NTK_ADDRESS = "KRALGUND (193302), NEAR GOVERNMENT HOSPITAL KRALGUND";
window.NTK_EMAIL = "ntofficeqaziabad@gmail.com";
window.NTK_OFFICE = [window.NTK_GOVERNMENT, window.NTK_DEPARTMENT, window.NTK_OFFICE_NAME, window.NTK_ADDRESS].join(" / ");
